# Generated by Django 2.2.4 on 2020-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True, verbose_name='评论内容'),
        ),
    ]
