# Generated by Django 2.2.4 on 2020-06-26 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200624_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['date_publish'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
